export const ProductDetails = [
	{
		id: 260,
		Thumbnails: 'image',
		ProductName: 'LG320E1K-A5-AC',
		category: 'Module',
		SKU: 'MH-13',
		Manufacturer: 'LG',
		InStock: 'yes',
		Qty: 150,
		ModelNumber: 'LG-101012',
		Promotion: 'New',
		Status: 'Active',
	},
	{
		id: 261,
		Thumbnails: 'image',
		ProductName: 'LG320E1K-A5-AC',
		category: 'Module',
		SKU: 'MH-13',
		Manufacturer: 'LG',
		InStock: 'yes',
		Qty: 150,
		ModelNumber: 'LG-101012',
		Promotion: 'New',
		Status: 'Active',
	},
	{
		id: 262,
		Thumbnails: 'image',
		ProductName: 'LG320E1K-A5-AC',
		category: 'Module',
		SKU: 'MH-13',
		Manufacturer: 'LG',
		InStock: 'yes',
		Qty: 150,
		ModelNumber: 'LG-101012',
		Promotion: 'New',
		Status: 'Active',
	},
	{
		id: 263,
		Thumbnails: 'image',
		ProductName: 'LG320E1K-A5-AC',
		category: 'Module',
		SKU: 'MH-13',
		Manufacturer: 'LG',
		InStock: 'yes',
		Qty: 150,
		ModelNumber: 'LG-101012',
		Promotion: 'New',
		Status: 'Active',
	},
	{
		id: 264,
		Thumbnails: 'image',
		ProductName: 'LG320E1K-A5-AC',
		category: 'Module',
		SKU: 'MH-13',
		Manufacturer: 'LG',
		InStock: 'yes',
		Qty: 150,
		ModelNumber: 'LG-101012',
		Promotion: 'New',
		Status: 'Active',
	},
	{
		id: 265,
		Thumbnails: 'image',
		ProductName: 'LG320E1K-A5-AC',
		category: 'Module',
		SKU: 'MH-13',
		Manufacturer: 'LG',
		InStock: 'yes',
		Qty: 150,
		ModelNumber: 'LG-101012',
		Promotion: 'New',
		Status: 'Active',
	},
	{
		id: 266,
		Thumbnails: 'image',
		ProductName: 'LG320E1K-A5-AC',
		category: 'Module',
		SKU: 'MH-13',
		Manufacturer: 'LG',
		InStock: 'yes',
		Qty: 150,
		ModelNumber: 'LG-101012',
		Promotion: 'New',
		Status: 'Active',
	},
];
