export const ERROR = "ERROR";
export const PENDING = "PENDING";
export const FETCH_LIBRARY = "FETCH_LIBRARY";
export const FETCH_LIBRARY_SUCCESS = "FETCH_LIBRARY_SUCCESS";
export const CREATE_LIBRARY = "CREATE_LIBRARY";
export const CREATE_LIBRARY_SUCCESS = "CREATE_LIBRARY_SUCCESS";
export const UPDATE_LIBRARY = "UPDATE_LIBRARY";
export const UPDATE_LIBRARY_SUCCESS = "UPDATE_LIBRARY_SUCCESS";
export const DELETE_LIBRARY = "DELETE_LIBRARY";
export const DELETE_LIBRARY_SUCCESS = "DELETE_LIBRARY_SUCCESS";


